services:

  jekyll:
    image: jekyll/jekyll:latest
    platform: linux/amd64
    command: bash -c "bundle install && jekyll serve --watch --force_polling --port 4042 --config '_config.yml,_config_dev.yml'"

    volumes:
      - ./:/app
      - ../zer0-mistakes:/zer0-mistakes:ro
      - bundle_cache:/usr/local/bundle
    ports:
      - "4042:4042"
      - "35730:35730"
    working_dir: /app
    environment:
      JEKYLL_ENV: development
      BUNDLE_PATH: /usr/local/bundle

volumes:
  bundle_cache: